### ISSUE TITLE
Some tests are failing locally but not with Travis CI

### ISSUE THREAD

**Issue by mpreu** [gfleury/go-bitbucket-v1#44]
As part of a previous [pull request](https://github.com/gfleury/go-bitbucket-v1/pull/39) I encountered a weird behaviour with some of the tests. This ticket is created as a result of the response by @gfleury.

I run `go version go1.13.6 linux/amd64` on `Fedora 31`.

Running the tests locally using `go test`results in (latest `master`):

```
--- FAIL: TestGetWebhooksResponse (0.00s)
    --- FAIL: TestGetWebhooksResponse/Empty_list (0.00s)
        api_response_test.go:293: GetWebhooksResponse() = [], want []
--- FAIL: TestGetUsersPermissionResponse (0.00s)
    --- FAIL: TestGetUsersPermissionResponse/Empty_list (0.00s)
        api_response_test.go:377: GetUsersPermissionResponse() = [], want []
```
On the local side these errors can be fixed easily e.g. with replacing the test for an empty slice with `nil` as in the following example:

```go
func TestGetWebhooksResponse(t *testing.T) {
	type args struct {
		r *APIResponse
	}
	tests := []struct {
		...
	}{
		{
			name: "Empty list",
                        ....
                        // Here we change the test
			want:    []Webhook{} => nil,
			wantErr: false,
		},
```
Unfortunately this fix does not apply when running the tests inside Travis CI. Travis CI is failing with the exact same error message as above. So I am in a situation where I can have successfully running tests either here or locally.

The initial guess was that the used go version here (1.11) was somehow part of this behaviour. But a test with an updated Travis CI go version did not fix this.

I was not able to track down the issue by now. I may have to cross reference the tests with a second go setup to exclude the possibility to have a problem on my side. (I currently doubt to see a difference with that)

**Comment by gfleury** [comment]
Hi @mpreu, after our original discussion I decided to extend the travis tests to different versions of go. 
Here we have the actual master running against 1.13.8 and passing. 

https://travis-ci.org/gfleury/go-bitbucket-v1/jobs/658861807

The odd part is that if you try the master now on your environment it will still fail, right?

**Comment by mpreu** [comment]
Hi @gfleury,

just checked it with an independent system (unfortunately as well `Fedora 31`, `go 1.13.6`, do not have another system setup available right now) using:

```
sudo dnf install go
cd /tmp && git clone <url> test && cd test
go get -d -v .
go test
```

Exactly the same errors occur.

Only obvious difference seems to be that Travis CI is running Ubuntu. Although cannot imagine a scenario where this should be a factor for basic stuff like this.

**Comment by gfleury** [comment]
Also mange to quick reproduce with, 
```
 docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.13.6 sh -c "go get . && go test"
```
I will get some time to investigate this.

**Comment by gfleury** [comment]
@mpreu can you check against master?
