### ISSUE TITLE
SSH Keys endpoints missing?

### ISSUE THREAD

**Issue by arve0** [gfleury/go-bitbucket-v1#59]
Hi! Seems like SSH-keys endpoints are missing?

API-documentation: https://docs.atlassian.com/bitbucket-server/rest/7.12.1/bitbucket-ssh-rest.html

**Comment by gfleury** [comment]
Partially, yes. Right now we cover only the global scope with these two:

https://github.com/gfleury/go-bitbucket-v1/blob/412cc3323e5e153af3ab85ec254b24b6a0722d6e/default_api.go#L7742
https://github.com/gfleury/go-bitbucket-v1/blob/412cc3323e5e153af3ab85ec254b24b6a0722d6e/default_api.go#L7797

For the per-project ssh keys we don't have it. But we are always open to PRs! =)

**Comment by arve0** [comment]
Thanks, I missed those. [Search for _ssh_](https://github.com/gfleury/go-bitbucket-v1/search?q=ssh) did not find them.

Anyhow, I'm interested in per repo. 

> But we are always open to PRs! =)

Do you write the OpenAPI spec per hand? I've transformed the [WADL from atlassian](https://docs.atlassian.com/bitbucket-server/rest/7.12.1/bitbucket-rest.wadl) with [api-spec-converter](https://github.com/LucyBot-Inc/api-spec-converter), which works, but misses the SSH-endpoints too. So I have a handwritten spec, by following the documentation.

If I send a PR, should that go into [docs](https://github.com/gfleury/go-bitbucket-v1/tree/master/docs)? 

I've also looked after how you generate the go-code. The readme states swagger-codegen is used, but I did not find any script/makefile with the exact command. How do you generate the go-code?
