### ISSUE TITLE
GetPullRequest takes an int PR id instead of an int64?

### ISSUE THREAD

**Issue by vlovich** [gfleury/go-bitbucket-v1#63]
The other API endpoints I've been using seem to use int64 but GetPullRequest seems to take in an int. Is this a typo?

**Comment by vlovich** [comment]
Another one is Merge takes int but CanMerge takes int64.

**Comment by gfleury** [comment]
Lets move it all to int. Seems that it diverged over time.

**Comment by gfleury** [comment]
Fixed by #78
