### ISSUE TITLE
does webhook secret validation work?

### ISSUE THREAD

**Issue by tooptoop4** [gfleury/go-bitbucket-v1#71]
https://github.com/argoproj/argo-events/blob/340627059538af49f095e497fdef1b9e888f393d/eventsources/sources/bitbucketserver/start.go#L290 references this lib
but curl requests to the webook still succeed without any webhook secret passed

i couldn't see something like https://github.com/go-playground/webhooks/blob/v5.17.0/bitbucket-server/bitbucketserver.go#L129-L141

**Comment by tooptoop4** [comment]
doesn't work

**Comment by gfleury** [comment]
Hey @tooptoop4 some endpoints are indeed missing some details. Not sure if this is one of them.
