### ISSUE TITLE
SetDefaultBranch doesn't accept a branch name

### ISSUE THREAD

**Issue by revathyrams** [gfleury/go-bitbucket-v1#76]
Bitbucket APIs support setting the default branch.
The SetDefaultBranch doesn't accept a branch name, neither does it include it in the request body.

**Comment by gfleury** [comment]
Hey, 
Thanks for reporting, some of the requests methods are empty because were never used. 
Fixed it, 
https://github.com/gfleury/go-bitbucket-v1/blob/master/default_api.go#L10234

you can call 
```
SetDefaultBranch("PRJ", "repo", "ref/branch/master")
```

**Comment by revathyrams** [comment]
Are you sure it's `"ref/branch/<branch-name>"?`

The documentation says it's
```
"refs/heads/<branch name>
```
https://docs.atlassian.com/bitbucket-server/rest/7.1.1/bitbucket-rest.html#idp205

**Comment by gfleury** [comment]
I'm sorry, I just wanted to point out that is a ref and not just the branch
name.
Follow the documentation for the correct ref.

Revathy Ramasundaram ***@***.***> schrieb am Do., 31. Aug.
2023, 02:25:
